options:
    image:
        type: string
        default: wordpress:php7.3
        description: The docker image to install.
    ports:
        type: string
        description: |
          Ports to expose, space separated list in name:8000 format. Names are alphanumeric + hyphen.
          For example: "http:80 metrics:7127"
        default: http:80
    container_config:
        type: string
        description: |
            YAML formatted map of container config keys & values. These are generally accessed from
            inside the image as environment variables. Can be used to configure customized Wordpress images.
        default: ""
    container_secrets:
        type: string
        description: |
            YAML formatted map of secrets. Works just like container_config,
        default: ""